import { z } from "zod";

export const workspaceIdSchema = z.uuid().transform((value) => value.toLowerCase());
export const accessLevelSchema = z.enum(["admin", "member"]);
export const businessRoleSchema = z.enum(["general", "developer"]);
const text = new TextEncoder();
export const workspaceNameSchema = z.string().trim().min(1).max(100).refine((value) => !/[\u0000-\u001f\u007f]/.test(value) && !/[\uD800-\uDFFF]/u.test(value) && text.encode(value).length <= 300);
export const invitationEmailSchema = z.email().max(254).transform((value) => value.toLowerCase());
export const invitationTokenSchema = z.string().regex(/^[A-Za-z0-9_-]{43}$/);
export const workspaceSchema = z.object({ id: workspaceIdSchema, name: workspaceNameSchema, owner_user_id: workspaceIdSchema, access_level: accessLevelSchema, business_role: businessRoleSchema }).strict();
export const workspaceListSchema = z.object({ workspaces: z.array(workspaceSchema), owned_count: z.number().int().min(0).max(50), ownership_limit: z.literal(50) }).strict();
export const workspaceCreateInputSchema = z.object({ key: workspaceIdSchema, name: workspaceNameSchema }).strict();
export const workspaceCreateResultSchema = z.object({ workspace: workspaceSchema, replayed: z.boolean() }).strict();
export const workspaceRenameInputSchema = z.object({ name: workspaceNameSchema }).strict();
export const workspaceMemberSchema = z.object({ user_id: workspaceIdSchema, display_name: z.string(), access_level: accessLevelSchema, business_role: businessRoleSchema }).strict();
export const workspaceMemberInputSchema = z.object({ access_level: accessLevelSchema, business_role: businessRoleSchema }).strict();
export const workspaceGroupSchema = z.object({ id: workspaceIdSchema, name: workspaceNameSchema, member_user_ids: z.array(workspaceIdSchema) }).strict();
export const workspaceGroupCreateInputSchema = workspaceCreateInputSchema;
export const workspaceGroupCreateResultSchema = z.object({ group: workspaceGroupSchema, replayed: z.boolean() }).strict();
export const workspaceGroupMemberInputSchema = z.object({ member: z.boolean() }).strict();
export const workspaceInvitationSchema = z.object({ id: workspaceIdSchema, email: invitationEmailSchema, expires_at: z.iso.datetime(), status: z.enum(["pending", "accepted", "revoked", "expired"]) }).strict();
export const ownershipTransferStatusSchema = z.enum(["pending", "accepted", "rejected", "cancelled", "expired"]);
export const ownershipTransferActionSchema = z.enum(["accept", "reject", "cancel"]);
export const ownershipTransferSchema = z.object({ id: workspaceIdSchema, from_user_id: workspaceIdSchema, to_user_id: workspaceIdSchema, expires_at: z.iso.datetime(), status: ownershipTransferStatusSchema }).strict().refine(value => value.from_user_id !== value.to_user_id);
export const ownershipTransferInputSchema = z.object({ key: workspaceIdSchema, to_user_id: workspaceIdSchema }).strict();
export const ownershipTransferResultSchema = z.object({ transfer: ownershipTransferSchema, replayed: z.boolean() }).strict();
export const workspaceDetailSchema = z.object({ workspace: workspaceSchema, members: z.array(workspaceMemberSchema), groups: z.array(workspaceGroupSchema), invitations: z.array(workspaceInvitationSchema), ownership_transfer: ownershipTransferSchema.refine(value => value.status === "pending").nullable() }).strict();
export const invitationCreateInputSchema = z.object({ key: workspaceIdSchema, email: invitationEmailSchema }).strict();
export const invitationCreateResultSchema = z.object({ id: workspaceIdSchema, token: invitationTokenSchema.nullable(), expires_at: z.iso.datetime(), replayed: z.boolean() }).strict().refine((value) => value.replayed === (value.token === null));
export const invitationAcceptInputSchema = z.object({ token: invitationTokenSchema }).strict();
export const invitationAcceptResultSchema = workspaceCreateResultSchema;
export const workspaceMutationResultSchema = z.object({ ok: z.literal(true) }).strict();
export const workspaceEmptyInputSchema = z.object({}).strict();
export type Workspace = z.infer<typeof workspaceSchema>;
export type WorkspaceList = z.infer<typeof workspaceListSchema>;
export type WorkspaceDetail = z.infer<typeof workspaceDetailSchema>;
export type WorkspaceGroup = z.infer<typeof workspaceGroupSchema>;
export type WorkspaceCreateInput = z.infer<typeof workspaceCreateInputSchema>;
export type WorkspaceCreateResult = z.infer<typeof workspaceCreateResultSchema>;
export type WorkspaceMemberInput = z.infer<typeof workspaceMemberInputSchema>;
export type InvitationCreateInput = z.infer<typeof invitationCreateInputSchema>;
export type InvitationCreateResult = z.infer<typeof invitationCreateResultSchema>;
export type WorkspaceMutationResult = z.infer<typeof workspaceMutationResultSchema>;
export type WorkspaceGroupCreateResult = z.infer<typeof workspaceGroupCreateResultSchema>;

export type OwnershipTransfer = z.infer<typeof ownershipTransferSchema>;
export type OwnershipTransferAction = z.infer<typeof ownershipTransferActionSchema>;
export type OwnershipTransferInput = z.infer<typeof ownershipTransferInputSchema>;
export type OwnershipTransferResult = z.infer<typeof ownershipTransferResultSchema>;
